### ISSUE TITLE
Error occurs when running testcpu.py

### ISSUE THREAD

**Issue by seekFire** [jinfagang/DCNv2_latest#16]
After building, when I run testcpu.py directly, the error occurs as follows:
`Traceback (most recent call last):
  File "/home/bst/Documents/Projects/Official/Object_Detection/BBAVectors-Oriented-Object-Detection/models/DCNv2/testcpu.py", line 255, in <module>
    example_dconv()
  File "/home/bst/Documents/Projects/Official/Object_Detection/BBAVectors-Oriented-Object-Detection/models/DCNv2/testcpu.py", line 175, in example_dconv
    output = dcn(input)
  File "/home/bst/anaconda2/envs/Python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bst/Documents/Projects/Official/Object_Detection/BBAVectors-Oriented-Object-Detection/models/DCNv2/dcn_v2.py", line 191, in forward
    self.deformable_groups,
  File "/home/bst/Documents/Projects/Official/Object_Detection/BBAVectors-Oriented-Object-Detection/models/DCNv2/dcn_v2.py", line 39, in forward
    ctx.deformable_groups,
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)`

**Comment by jinfagang** [comment]
CPU am not tested actually. Please send PR if you got a chance to fix it.

**Comment by DUTxutengfei** [comment]
I have the same problem

**Comment by shitouren1994** [comment]
i have the same problem

**Comment by songkq** [comment]
the same issue
