### ISSUE TITLE
DCN v2 compilation for RTX 3080

### ISSUE THREAD

**Issue by capricornfati** [jinfagang/DCNv2_latest#24]
Hello,

I am not able to compile DCN v2. My configuration is the following:

conda 4.9.2
python 3.8.8
pytorch 1.8.1
Build cuda_11.2.r11.2/compiler.29618528_0
driver version: 460.39
CUDA Version 11.2

I have tried many DCN v2 forks to compile but I was not able succeed.
Any help would be appreciated :)

Thank you
Fatih.

**Comment by jinfagang** [comment]
I am OK on both RTX3080 and pytorch 1.8 with CUDA11. Please make sure you using this fork.

**Comment by rtgunti** [comment]
Hey @capricornfati 

If you are using a virtual environment, make sure you activate it by adding this line at the beginning of make.sh
source <absolute_path_to_virtualenv>/bin/activate

Also, change the line from 'sudo python setup.py build develop' to 'python setup.py build develop' in make.sh

**Comment by capricornfati** [comment]
> Hey @capricornfati
> 
> If you are using a virtual environment, make sure you activate it by adding this line at the beginning of make.sh
> source <absolute_path_to_virtualenv>/bin/activate
> 
> Also, change the line from 'sudo python setup.py build develop' to 'python setup.py build develop' in make.sh

Hello,

I have been experimenting in conda environment. I install cuda tool kit, torchvision and torch according to pytorch locally instructions. I removed “sudo”  in make.sh before. I haven’t tried to install pytorch on the system (without any virtual environment) yet. I will try it. Thank you

**Comment by capricornfati** [comment]
> I am OK on both RTX3080 and pytorch 1.8 with CUDA11. Please make sure you using this fork.

Do you use anaconda?
Could you please give detailed information about your system?
os version
nvcc version (cuda)
nvidia-smi output
anaconda version
python version
pytorch version

**Comment by capricornfati** [comment]
> Hey @capricornfati
> 
> If you are using a virtual environment, make sure you activate it by adding this line at the beginning of make.sh
> source <absolute_path_to_virtualenv>/bin/activate
> 
> Also, change the line from 'sudo python setup.py build develop' to 'python setup.py build develop' in make.sh

I already did operations in activated conda environment so I think no need to activate python environment. 
Any help would be appreciated

**Comment by AiueoABC** [comment]
I'm not sure this is same issue but hope this helps. #40

**Comment by sumit-agrwl** [comment]
@capricornfati I am getting the following error : 

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    setup(
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/usr0/home/sumita/miniconda3/envs/FairMOT/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

os version
nvcc version (cuda) : 9.1
nvidia-smi output : GeForce GTX 1080
anaconda version : latest
python version : 3.8
pytorch version : 1.8.0

**Comment by Eunjnnn** [comment]
@sumit-agrwl hello. Although a lot of time has passed but,, did you solve above issue?
