### ISSUE TITLE
Runtime Error: Error compiling objects for extension

### ISSUE THREAD

**Issue by jashanvirtaggar** [jinfagang/DCNv2_latest#51]
python setup.py build_ext --inplace
running build_ext
C:\Anaconda4\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'ext_cpu' extension
Emitting ninja build file C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Anaconda4\lib\site-packages\torch\include -IC:\Anaconda4\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda4\lib\site-packages\torch\include\TH -IC:\Anaconda4\lib\site-packages\torch\include\THC -IC:\Anaconda4\include -IC:\Anaconda4\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp /FoC:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext/ext_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ext_cpu -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
C:\Anaconda4\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(389): warning C4101: 'e': unreferenced local variable
C:\Anaconda4\lib\site-packages\torch\include\pybind11\detail/common.h(106): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\Anaconda4\include\pyerrors.h(489): note: see previous definition of 'HAVE_SNPRINTF'
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp(29): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp(52): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp(78): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp(98): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp(121): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cpu.cpp(160): warning C4996: 'at::Tensor::data': Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Anaconda4\lib\site-packages\torch\lib /LIBPATH:C:\Anaconda4\libs /LIBPATH:C:\Anaconda4\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_ext_cpu C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext/ext_cpu.obj /OUT:build\lib.win-amd64-3.6\ext_cpu.cp36-win_amd64.pyd /IMPLIB:C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext\ext_cpu.cp36-win_amd64.lib
   Creating library C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext\ext_cpu.cp36-win_amd64.lib and object C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext\ext_cpu.cp36-win_amd64.exp    
Generating code
Finished generating code
building 'ext_cuda' extension
Emitting ninja build file C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Anaconda4\lib\site-packages\torch\include -IC:\Anaconda4\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda4\lib\site-packages\torch\include\TH -IC:\Anaconda4\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -IC:\Anaconda4\include -IC:\Anaconda4\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_kernel.cu -o C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext/ext_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ext_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/build/temp.win-amd64-3.6/Release/ext/ext_kernel.obj 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler 
/wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Anaconda4\lib\site-packages\torch\include -IC:\Anaconda4\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda4\lib\site-packages\torch\include\TH -IC:\Anaconda4\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA 
GPU Computing Toolkit\CUDA\v11.2\include" -IC:\Anaconda4\include -IC:\Anaconda4\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_kernel.cu -o C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext/ext_kernel.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ext_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/ext/ext_kernel.cu(11): error: no instance of constructor "NNFunctor<T, dim>::NNFunctor [with T=double, dim=3]" matches the argument list
            argument types are: (double *, double *, int64_t, int64_t, long *)

C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/ext/ext_kernel.cu(11): error: no instance of constructor "NNFunctor<T, dim>::NNFunctor [with T=float, dim=3]" matches the argument list
            argument types are: (float *, float *, int64_t, int64_t, long *)

C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/ext/ext_kernel.cu(24): error: no instance of constructor "CrossCheckFunctor::CrossCheckFunctor" matches the argument list
            argument types are: (long *, long *, int64_t, int64_t, uint8_t *)

C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/ext/ext_kernel.cu(33): error: no instance of constructor "ProjNNFunctor<T, dim>::ProjNNFunctor [with T=double, dim=3]" matches the argument list
            argument types are: (double *, double *, double *, int64_t, int64_t, int64_t, int, long *)

C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/ext/ext_kernel.cu(33): error: no instance of constructor "ProjNNFunctor<T, dim>::ProjNNFunctor [with T=float, dim=3]" matches the argument list
            argument types are: (float *, float *, float *, int64_t, int64_t, int64_t, int, long *)

5 errors detected in the compilation of "C:/Users/jtaggar/Work/ConnectingTheDots/connecting_the_dots-master/connecting_the_dots-master/torchext/ext/ext_kernel.cu".
ext_kernel.cu
[2/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Anaconda4\lib\site-packages\torch\include -IC:\Anaconda4\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda4\lib\site-packages\torch\include\TH -IC:\Anaconda4\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -IC:\Anaconda4\include -IC:\Anaconda4\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp /FoC:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\build\temp.win-amd64-3.6\Release\ext/ext_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=ext_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
C:\Anaconda4\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(389): warning C4101: 'e': unreferenced local variable
C:\Anaconda4\lib\site-packages\torch\include\pybind11\detail/common.h(106): warning C4005: 'HAVE_SNPRINTF': macro redefinition
C:\Anaconda4\include\pyerrors.h(489): note: see previous definition of 'HAVE_SNPRINTF'
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(10): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(11): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(32): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(33): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(48): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(49): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(50): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(74): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(75): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(93): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(94): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(110): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, 
so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(111): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, 
so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
C:\Users\jtaggar\Work\ConnectingTheDots\connecting_the_dots-master\connecting_the_dots-master\torchext\ext\ext_cuda.cpp(112): warning C4996: 'at::Tensor::type': Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, 
so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device().
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Anaconda4\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "C:\Anaconda4\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    include_dirs=include_dirs
  File "C:\Anaconda4\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Anaconda4\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Anaconda4\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda4\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Anaconda4\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Anaconda4\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Anaconda4\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Anaconda4\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Anaconda4\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Anaconda4\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Anaconda4\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Anaconda4\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Anaconda4\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Anaconda4\lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Anaconda4\lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Anaconda4\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by 123chu123** [comment]
Hello, I'm encountering the same problem now. How did you solve it in the end?
